import { Router } from 'express';
import { authRouter } from './auth.routes';
import { userRouter } from './user.routes';
import { nutritionRouter } from './nutrition.routes';
import { fitnessRouter } from './fitness.routes';
import { sleepRouter } from './sleep.routes';
import { healthRouter } from './health.routes';
import { aiRouter } from './ai.routes';
import { hydrationRouter } from './hydration.routes';
import { goalsRouter } from './goals.routes';
import { habitsRouter } from './habits.routes';
import { coachRouter } from './coach.routes';
import { myPlanRouter } from './myplan.routes';
import { importRouter } from './import.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/nutrition', nutritionRouter);
apiRouter.use('/fitness', fitnessRouter);
apiRouter.use('/sleep', sleepRouter);
apiRouter.use('/hydration', hydrationRouter);
apiRouter.use('/goals', goalsRouter);
apiRouter.use('/habits', habitsRouter);
apiRouter.use('/coach', coachRouter);
apiRouter.use('/my-plan', myPlanRouter);
apiRouter.use('/import', importRouter);
apiRouter.use('/health', healthRouter);
apiRouter.use('/ai', aiRouter);
